### ISSUE TITLE
Upgrade to PyBEL 14 / Bio2BEL 3

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/reactome#14]
Blocked by:
- [x] Upgrade Bio2BEL with PyBEL 14 https://github.com/bio2bel/bio2bel/pull/24
- [x] Upgrade ComPath Utils with new PyBEL/Bio2BEL https://github.com/ComPath/ComPath-Utils/issues/5 
- [ ] Upgrade Bio2BEL-HGNC with new PyBEL/Bio2BEL https://github.com/bio2bel/hgnc/pull/10
- [ ] Upgrade Bio2BEL-ChEBI with new PyBEL/Bio2BEL https://github.com/bio2bel/chebi/issues/8

**Comment by djinnome** [comment]
Hi folks,

I have the following error when I try to populate `bio2bel_reactome`

```python
bash-3.2$ bio2bel_reactome populate
Traceback (most recent call last):
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/bin/bio2bel_reactome", line 10, in <module>
    sys.exit(main())
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/bio2bel/manager/cli_manager.py", line 38, in main
    ctx.obj = cls(connection=connection)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/bio2bel_reactome/manager.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/compath_utils/manager.py", line 46, in __init__
    raise TypeError(f'{self.pathway_model} should inherit from {CompathPathwayMixin}')
TypeError: <class 'bio2bel_reactome.models.Pathway'> should inherit from <class 'compath_utils.models.CompathPathwayMixin'>
bash-3.2$ 
```

When I try to install the latest version of `bio2bel_reactome` it downgrades pybel to `pybel-0.14.1`, which is too old for `pybel-jupyter` `covid19kg`  and `bel-repository` but too recent for   `bio2bel-wikipathways`, `compath`, and `bio2bel-chebi`:

```python
bash$ pip install --upgrade bio2bel_reactome
Requirement already up-to-date: bio2bel_reactome in /Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages (0.2.4.dev0)
tmapper->pyobo>=0.1.1->bio2bel>=0.2.1->bio2bel_reactome) (0.15.2)
...
ERROR: pybel-jupyter 0.3.0 has requirement pybel>=0.14.7, but you'll have pybel 0.14.1 which is incompatible.
ERROR: covid19kg 0.0.1 has requirement bel-repository==0.1.0, but you'll have bel-repository 0.1.1 which is incompatible.
ERROR: covid19kg 0.0.1 has requirement pybel>=0.14.6, but you'll have pybel 0.14.1 which is incompatible.
ERROR: compath 0.1.3.dev0 has requirement bio2bel==0.2.1, but you'll have bio2bel 0.3.6 which is incompatible.
ERROR: compath 0.1.3.dev0 has requirement flask==1.0.2, but you'll have flask 1.1.1 which is incompatible.
ERROR: compath 0.1.3.dev0 has requirement pybel==0.13.2, but you'll have pybel 0.14.1 which is incompatible.
ERROR: compath 0.1.3.dev0 has requirement sqlalchemy==1.3.3, but you'll have sqlalchemy 1.3.8 which is incompatible.
ERROR: bio2bel-chebi 0.2.2.dev0 has requirement bio2bel<0.3.0,>=0.2.0, but you'll have bio2bel 0.3.6 which is incompatible.
ERROR: bio2bel-chebi 0.2.2.dev0 has requirement pybel<0.14.0,>=0.13.1, but you'll have pybel 0.14.1 which is incompatible.
ERROR: bel-repository 0.1.1 has requirement pybel<0.15.0,>=0.14.8, but you'll have pybel 0.14.1 which is incompatible.
ERROR: bio2bel-wikipathways 0.2.4.dev0 has requirement bio2bel<0.3.0,>=0.2.0, but you'll have bio2bel 0.3.6 which is incompatible.
ERROR: bio2bel-wikipathways 0.2.4.dev0 has requirement pybel<0.14.0,>=0.13.1, but you'll have pybel 0.14.1 which is incompatible.
Installing collected packages: pybel
  Attempting uninstall: pybel
    Found existing installation: pybel 0.14.9
    Uninstalling pybel-0.14.9:
      Successfully uninstalled pybel-0.14.9
Successfully installed pybel-0.14.1
```
